# Generated by Django 4.2.3 on 2024-02-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('published', 'published'), ('unpublished', 'unpublished'), ('banned', 'banned')], default='unpublished', max_length=16)),
                ('created_at', models.DateTimeField()),
                ('published_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('quaerat', 'quaerat'), ('etincidunt', 'etincidunt'), ('dolorem', 'dolorem'), ('modi', 'modi'), ('amet', 'amet')], max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
