# Generated by Django 4.2.3 on 2024-02-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_alter_post_created_at_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('quaerat', 'quaerat'), ('etincidunt', 'etincidunt'), ('dolorem', 'dolorem'), ('modi', 'modi'), ('amet', 'amet')], max_length=64, null=True),
        ),
    ]
