# Generated by Django 4.2.3 on 2024-03-01 04:07

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('quaerat', 'quaerat'), ('etincidunt', 'etincidunt'), ('dolorem', 'dolorem'), ('modi', 'modi'), ('amet', 'amet')], max_length=64, null=True, validators=[challenges.models.LoremCategory.validate_category]),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('unpublished', 'unpublished'), ('banned', 'banned')], default='unpublished', max_length=16, validators=[challenges.models.PostStatus.validate_status]),
        ),
    ]
