# Generated by Django 4.2.3 on 2024-03-01 05:46

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_post_category_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'published'), ('unpublished', 'unpublished'), ('banned', 'banned')], default=challenges.models.PostStatus['unpublished'], max_length=16, validators=[challenges.models.PostStatus.validate_status]),
        ),
    ]
