# Generated by Django 4.2.3 on 2024-03-02 04:54

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_alter_post_created_at_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('quaerat', 'quaerat'), ('etincidunt', 'etincidunt'), ('dolorem', 'dolorem'), ('modi', 'modi'), ('amet', 'amet'), ('none', None)], max_length=64, null=True, validators=[challenges.models.LoremCategory.validate_category]),
        ),
    ]
